name: Argus CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
         # Enable caching of the ~/.m2/repository so artifacts persist
         cache-read-only: false
      
    - name: Build with Gradle Wrapper
      run: ./gradlew build --no-daemon

    - name: Run Benchmark
      continue-on-error: true
      run: |
        ./gradlew :utilities:benchmark:runBenchmark --quiet > benchmark_report.md
        cat benchmark_report.md >> $GITHUB_STEP_SUMMARY
